<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DefaultImage', 'doctrine');

/**
 * BaseDefaultImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property string $image
 * 
 * @method string       getName()  Returns the current record's "name" value
 * @method string       getTitle() Returns the current record's "title" value
 * @method string       getImage() Returns the current record's "image" value
 * @method DefaultImage setName()  Sets the current record's "name" value
 * @method DefaultImage setTitle() Sets the current record's "title" value
 * @method DefaultImage setImage() Sets the current record's "image" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDefaultImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('default_image');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $imagebuilder0 = new Doctrine_Template_ImageBuilder(array(
             ));
        $this->actAs($imagebuilder0);
    }
}