<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TextBlock', 'doctrine');

/**
 * BaseTextBlock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property string $text
 * @property string $application
 * @property string $module
 * @property string $special_mark
 * @property boolean $is_visible_for_admin
 * 
 * @method string    getName()                 Returns the current record's "name" value
 * @method string    getTitle()                Returns the current record's "title" value
 * @method string    getText()                 Returns the current record's "text" value
 * @method string    getApplication()          Returns the current record's "application" value
 * @method string    getModule()               Returns the current record's "module" value
 * @method string    getSpecialMark()          Returns the current record's "special_mark" value
 * @method boolean   getIsVisibleForAdmin()    Returns the current record's "is_visible_for_admin" value
 * @method TextBlock setName()                 Sets the current record's "name" value
 * @method TextBlock setTitle()                Sets the current record's "title" value
 * @method TextBlock setText()                 Sets the current record's "text" value
 * @method TextBlock setApplication()          Sets the current record's "application" value
 * @method TextBlock setModule()               Sets the current record's "module" value
 * @method TextBlock setSpecialMark()          Sets the current record's "special_mark" value
 * @method TextBlock setIsVisibleForAdmin()    Sets the current record's "is_visible_for_admin" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTextBlock extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('text_block');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('application', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('module', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('special_mark', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('is_visible_for_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));


        $this->index('section_index', array(
             'fields' => 
             array(
              0 => 'application',
              1 => 'module',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'text',
             ),
             ));
        $this->actAs($i18n0);
    }
}