<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FloorSpacer', 'doctrine');

/**
 * BaseFloorSpacer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $restaurant_id
 * @property integer $floor_id
 * @property integer $width
 * @property integer $height
 * @property integer $posx
 * @property integer $posy
 * @property Floor $Floor
 * @property Restaurant $Restaurant
 * 
 * @method integer     getRestaurantId()  Returns the current record's "restaurant_id" value
 * @method integer     getFloorId()       Returns the current record's "floor_id" value
 * @method integer     getWidth()         Returns the current record's "width" value
 * @method integer     getHeight()        Returns the current record's "height" value
 * @method integer     getPosx()          Returns the current record's "posx" value
 * @method integer     getPosy()          Returns the current record's "posy" value
 * @method Floor       getFloor()         Returns the current record's "Floor" value
 * @method Restaurant  getRestaurant()    Returns the current record's "Restaurant" value
 * @method FloorSpacer setRestaurantId()  Sets the current record's "restaurant_id" value
 * @method FloorSpacer setFloorId()       Sets the current record's "floor_id" value
 * @method FloorSpacer setWidth()         Sets the current record's "width" value
 * @method FloorSpacer setHeight()        Sets the current record's "height" value
 * @method FloorSpacer setPosx()          Sets the current record's "posx" value
 * @method FloorSpacer setPosy()          Sets the current record's "posy" value
 * @method FloorSpacer setFloor()         Sets the current record's "Floor" value
 * @method FloorSpacer setRestaurant()    Sets the current record's "Restaurant" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFloorSpacer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('floor_spacer');
        $this->hasColumn('restaurant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('floor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('width', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('height', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('posx', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('posy', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Floor', array(
             'local' => 'floor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Restaurant', array(
             'local' => 'restaurant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}