<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FloorPlace', 'doctrine');

/**
 * BaseFloorPlace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $restaurant_id
 * @property integer $floor_id
 * @property integer $width
 * @property integer $height
 * @property integer $posx
 * @property integer $posy
 * @property string $number
 * @property integer $min_persons
 * @property integer $max_persons
 * @property Floor $Floor
 * @property Restaurant $Restaurant
 * 
 * @method integer    getRestaurantId()  Returns the current record's "restaurant_id" value
 * @method integer    getFloorId()       Returns the current record's "floor_id" value
 * @method integer    getWidth()         Returns the current record's "width" value
 * @method integer    getHeight()        Returns the current record's "height" value
 * @method integer    getPosx()          Returns the current record's "posx" value
 * @method integer    getPosy()          Returns the current record's "posy" value
 * @method string     getNumber()        Returns the current record's "number" value
 * @method integer    getMinPersons()    Returns the current record's "min_persons" value
 * @method integer    getMaxPersons()    Returns the current record's "max_persons" value
 * @method Floor      getFloor()         Returns the current record's "Floor" value
 * @method Restaurant getRestaurant()    Returns the current record's "Restaurant" value
 * @method FloorPlace setRestaurantId()  Sets the current record's "restaurant_id" value
 * @method FloorPlace setFloorId()       Sets the current record's "floor_id" value
 * @method FloorPlace setWidth()         Sets the current record's "width" value
 * @method FloorPlace setHeight()        Sets the current record's "height" value
 * @method FloorPlace setPosx()          Sets the current record's "posx" value
 * @method FloorPlace setPosy()          Sets the current record's "posy" value
 * @method FloorPlace setNumber()        Sets the current record's "number" value
 * @method FloorPlace setMinPersons()    Sets the current record's "min_persons" value
 * @method FloorPlace setMaxPersons()    Sets the current record's "max_persons" value
 * @method FloorPlace setFloor()         Sets the current record's "Floor" value
 * @method FloorPlace setRestaurant()    Sets the current record's "Restaurant" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFloorPlace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('floor_place');
        $this->hasColumn('restaurant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('floor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('width', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('height', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('posx', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('posy', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('number', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('min_persons', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 1,
             'length' => 2,
             ));
        $this->hasColumn('max_persons', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 1,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Floor', array(
             'local' => 'floor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Restaurant', array(
             'local' => 'restaurant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}