<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Restaurant', 'doctrine');

/**
 * BaseRestaurant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $admin_id
 * @property string $name
 * @property sfGuardUser $Admin
 * @property Doctrine_Collection $ConfigRecords
 * @property Doctrine_Collection $Floors
 * @property Doctrine_Collection $Spacers
 * @property Doctrine_Collection $Places
 * 
 * @method integer             getAdminId()       Returns the current record's "admin_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method sfGuardUser         getAdmin()         Returns the current record's "Admin" value
 * @method Doctrine_Collection getConfigRecords() Returns the current record's "ConfigRecords" collection
 * @method Doctrine_Collection getFloors()        Returns the current record's "Floors" collection
 * @method Doctrine_Collection getSpacers()       Returns the current record's "Spacers" collection
 * @method Doctrine_Collection getPlaces()        Returns the current record's "Places" collection
 * @method Restaurant          setAdminId()       Sets the current record's "admin_id" value
 * @method Restaurant          setName()          Sets the current record's "name" value
 * @method Restaurant          setAdmin()         Sets the current record's "Admin" value
 * @method Restaurant          setConfigRecords() Sets the current record's "ConfigRecords" collection
 * @method Restaurant          setFloors()        Sets the current record's "Floors" collection
 * @method Restaurant          setSpacers()       Sets the current record's "Spacers" collection
 * @method Restaurant          setPlaces()        Sets the current record's "Places" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRestaurant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('restaurant');
        $this->hasColumn('admin_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Admin', array(
             'local' => 'admin_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('RestaurantConfig as ConfigRecords', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));

        $this->hasMany('Floor as Floors', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));

        $this->hasMany('FloorSpacer as Spacers', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));

        $this->hasMany('FloorPlace as Places', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             'builder' => 'ProjectHelper::slug_builder',
             ));
        $this->actAs($sluggable0);
    }
}