<?php

/**
 * DefaultImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DefaultImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DefaultImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DefaultImage');
    }
}