<?php

/**
 * DefaultImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DefaultImage extends BaseDefaultImage
{
    public function getPhotoPath()
    {
        return '/uploads/default_image/' . $this->getImage();
    }
    
    public function getImageThumbnail($name = 'small')
    {
        $aThumbs = sfConfig::get('app_' . sfInflector::underscore(get_class($this)) . '_thumbs');
        if(isset($aThumbs[$name])){
            return $this->getPhotoPath() . $aThumbs[$name]['ext'];
        }
        $arr_name = explode('_', $name);
        if(isset($aThumbs[$arr_name[0]])){
            return $this->getPhotoPath() . $aThumbs[$arr_name[0]]['ext'];
        }
        return $this->getPhotoPath();
    }
    
    public static function getOne()
    {
        return Doctrine::getTable('DefaultImage')
                ->createQuery('i')
                ->fetchOne()
                ;
    }
}