<?php

/**
 * FloorSpacerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FloorSpacerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FloorSpacerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FloorSpacer');
    }
}