<?php

/**
 * FloorPlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FloorPlaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FloorPlaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FloorPlace');
    }
}