<?php

/**
 * FloorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FloorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FloorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Floor');
    }


    public function tmListRestaurant(Doctrine_Query $q){
        $a = $q->getRootAlias();
        $q->andWhere("$a.restaurant_id = ?", sfContext::getInstance()->getUser()->getGuardUser()->getRestaurant()->getId());
        return $q;
    }
}