<?php

/**
 * RestaurantConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RestaurantConfig extends BaseRestaurantConfig
{
    public function getRealValue($key_only = false) {
        switch($this->datatype){
            case 'enum':
                $expl = explode('::', $this->value);
                $value = array_pop($expl);
                if($this->label && !$key_only){
                    $labels = explode('|', $this->label);
                    $keys = explode('|', $expl[0]);
                    $key = array_search($value, $keys);
                    $value = !empty($labels[$key]) ? $labels[$key] : $value;
                }
                return $value;
            default:
                return $this->value;
        }
    }

    public function getOptions() {
        $options = array();
        $expl = explode('::', $this->value);
        $keys = explode('|', $expl[0]);
        if($this->label){
            $labels = explode('|', $this->label);
        }else{
            $labels = $keys;
        }
        foreach($keys as $k => $key){
            $options[$key] = $labels[$k];
        }
        return $options;
    }
}
