<?php

/**
 * RestaurantConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RestaurantConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RestaurantConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RestaurantConfig');
    }
    public function tmListRestaurant(Doctrine_Query $q) {
        $a = $q->getRootAlias();
        $q->andWhere("$a.restaurant_id = ?", sfContext::getInstance()->getUser()->getRestaurantId());
        return $q;
    }
}