<?php

/**
 * TextBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TextBlockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TextBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TextBlock');
    }
    
    public function tmListNormal(Doctrine_Query $q)
    {
        $a = $q->getRootAlias();
        return $q->addWhere("$a.is_visible_for_admin = ?", true);
    }
}