<?php

/**
 * Created by PhpStorm.
 * User: alexradyuk
 * Date: 2/2/18
 * Time: 22:40
 */
class sfGuardUserAdminFormUser extends sfGuardUserAdminForm
{
    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub


        $this->useFields(array('password', 'password_again'));
    }
}