restaurant_config:
  class: sfDoctrineRouteCollection
  options:
    model:                RestaurantConfig
    module:               restaurant_config
    prefix_path:          /restaurant_config
    column:               id
    with_wildcard_routes: true

floorplace_update:
  url: /floor/updatePlace
  param: {module: floor, action: updatePlace}

restaurant_admin:
  url: /restaurant/:id/admin
  param: {module: restaurant, action: admin}

floor:
  class: sfDoctrineRouteCollection
  options:
    model:                Floor
    module:               floor
    prefix_path:          /floor
    column:               id
    with_wildcard_routes: true

restaurant:
  class: sfDoctrineRouteCollection
  options:
    model:                Restaurant
    module:               restaurant
    prefix_path:          /restaurant
    column:               id
    with_wildcard_routes: true

sf_guard_user_user_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user_user
    prefix_path:          /user_user
    column:               id
    with_wildcard_routes: true




text_block:
  class: sfDoctrineRouteCollection
  options:
    model:                TextBlock
    module:               text_block
    prefix_path:          /text_block
    column:               id
    with_wildcard_routes: true



default_image:
  class: sfDoctrineRouteCollection
  options:
    model:                DefaultImage
    module:               default_image
    prefix_path:          /default_image
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options: { model: sfGuardUser, module: user, prefix_path: /user, column: id, with_wildcard_routes: true }

homepage:
  url: /
  param: { module: dashboard, action: index}
default_index:
  url: '/:module'
  param: { action: index }
default:
  url: '/:module/:action/*'
